#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
